PrimerParcial/Models/ErrorViewModel.cs
namespace PrimerParcial.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PrimerParcial/Models/NumeroModel.cs
using System.ComponentModel.DataAnnotations;

namespace PrimerParcial.Models
{
    public class NumeroModel
    {
        public int Num1 { get; set; }
        public int Num2 { get; set; }
        public int Num3 { get; set; }
        public string Resultado { get; set; }
    }
}

PrimerParcial/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using PrimerParcial.Models;
using System.Diagnostics;

namespace PrimerParcial.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Github()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PrimerParcial/Controllers/NumeroController.cs
using Microsoft.AspNetCore.Mvc;
using PrimerParcial.Models;
using System.ComponentModel.DataAnnotations;

namespace PrimerParcial.Controllers
{
    public class NumeroController : Controller
    {
        public IActionResult Calcular()
        {
            return View("NumeroView");
        }

        public IActionResult NumRand(NumeroModel ObjNumero)
        {
            if (ObjNumero.Num1 > ObjNumero.Num2)
            {
                ObjNumero.Resultado = "El Numero Minimo no puede ser mayor al Numero Maximo";
                return View("NumeroView", ObjNumero);
            }
            else
            {
                Random NumRand = new Random();
                ObjNumero.Num3 = NumRand.Next(ObjNumero.Num1, ObjNumero.Num2 + 1);
                ObjNumero.Resultado = "El numero al azar es: " + ObjNumero.Num3;
                return View("NumeroView", ObjNumero);

            }
        }
    }
}

PrimerParcial/Views/Home/Github.cshtml
@{
	ViewData["Title"] = "Repositorio GitHub";
}
<h1>@ViewData["Title"]</h1>

<p>El presente proyecto ha sido publicado en GitHub en acorde a las instrucciones del Examen Parcial; el enlace se proporciona <a href="https://github.com/Fernando2413/PrimerParcial-Carlos.241403.git">aqui</a>.</p>

PrimerParcial/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Pagina de Inicio";
}
<h1>@ViewData["Title"]</h1>

<p>Bienvenido a la aplicación del primer examen parcial del curso de Programación III, selecciona la pestaña <a>"Calcular"</a> para comenzar.</p>

PrimerParcial/Views/Numero/NumeroView.cshtml
@model PrimerParcial.Models.NumeroModel
@{
    ViewData["Title"] = "Calcular";
}
<div>
    <h1>Calculadora de Numero al Azar</h1>
    <p>Introduzca dos numeros que correspondan al limite inferior y superior de un rango de numeros, con el fin de generar un numero al azar que pertenezca a dicho rango. <a> Ambos limites son Inclusivos</a></a></p>
    <form asp-controller="Numero" asp-action="NumRand">
        <table>
            <tr>
                <td><label>Numero Minimo</label></td>
                <td><input asp-for="Num1"></td>
            </tr>
            <tr>
                <td><label>Numero Maximo</label></td>
                <td><input asp-for="Num2"></td>
            </tr>
            <tr>
                <td><input type="submit" value="Generar"></td>
            </tr>
        </table>
    </form>
    <p>@Html.DisplayTextFor(model => model.Resultado)</p>
</div>

PrimerParcial/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Primer Examen Parcial</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PrimerParcial.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Primer Examen Parcial</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Numero" asp-action="Calcular">Calcular</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Github">GitHub</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacidad</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - PrimerParcial - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacidad</a> <a>- Elaborado por Carlos Fernando Hernandez León</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>